### PR TITLE
vagrant(coverage): check for (possibly) missing coverage

### PR DESCRIPTION
**Pull request by mrc0mmand**
If the test logs contain lines like:

```
...systemd-resolved[735885]: profiling:/systemd-meson-build/src/shared/libsystemd-shared-250.a.p/base-filesystem.c.gcda:Cannot open
```

it means we're possibly missing some coverage since gcov can't write the stats,
usually due to the sandbox being too restrictive (e.g. ProtectSystem=yes,
ProtectHome=yes) or the $BUILD_DIR being inaccessible to non-root users.

### CODE REVIEW

**Comment by evverx** [comment]
@mrc0mmand I think it's a nice way to increase the coverage but I think at some point new tests should be added :-)

By the way, I noticed that the coverage went up a little a couple days ago (without new tests). I wonder what caused it?

**Comment by mrc0mmand** [comment]
> @mrc0mmand I think it's a nice way to increase the coverage but I think at some point new tests should be added :-)

Indeed, that's definitely on my radar :-)

> 
> By the way, I noticed that the coverage went up a little a couple days ago (without new tests). I wonder what caused it?

That most likely https://github.com/systemd/systemd-centos-ci/commit/57802f1eb121194b15612383801ca9b640533aad (which was prompted by https://github.com/systemd/systemd/pull/22481#issuecomment-1036081066 and also resulted in this PR).

**Comment by evverx** [comment]
Thanks! What's weird though is that the badge shows 52% (instead of 58%). As far as I can see the coverage went down and then it went up but the badge somehow wasn't updated. Not that it matters though :-)

**Comment by mrc0mmand** [comment]
> Thanks! What's weird though is that the badge shows 52% (instead of 58%). As far as I can see the coverage went down and then it went up but the badge somehow wasn't updated. Not that it matters though :-)

Yeah, the drop was caused by me screwing up the mentioned "fix" the first time. Let's hope the badge is just cached somewhere and gets updated soon :-)

**Comment by evverx** [comment]
> Let's hope the badge is just cached somewhere and gets updated soon :-)

It seems to be the case. My browser caches that badge so I still see 52% but in incognito mode it's fine

**Pull request merged**
