### PR TITLE
vagrant: let's enable TEST-01-BASIC under clang+ASan

### PR DESCRIPTION
**Pull request by mrc0mmand**

### CODE REVIEW

**Comment by mrc0mmand** [comment]
@evverx this is interesting - the tests report success even though most of the services failed to start :-)

```
[FAILED] Failed to start Create System Users.
[FAILED] Failed to start Create Static Device Nodes in /dev.
[FAILED] Failed to start Journal Service.
[FAILED] Failed to start Journal Service.
[FAILED] Failed to start Journal Service.
[FAILED] Failed to start Journal Service.
[FAILED] Failed to start Journal Service.
[FAILED] Failed to listen on Journal Audit Socket.
[FAILED] Failed to start Journal Service.
[FAILED] Failed to start Create Volatile Files and Directories.
[FAILED] Failed to start Update UTMP about System Boot/Shutdown.
[FAILED] Failed to start Rebuild Journal Catalog.
[FAILED] Failed to start Update is Completed.
[FAILED] Failed to start Login Service.
[FAILED] Failed to start Login Service.
[FAILED] Failed to start Permit User Sessions.
[FAILED] Failed to start Login Service.
[FAILED] Failed to start Login Service.
[FAILED] Failed to start Login Service.
[FAILED] Failed to start Login Service.
[FAILED] Failed to start End the test.
[FAILED] Failed to start Rebuild Hardware Database.
[FAILED] Failed to start Apply Kernel Variables.
[FAILED] Failed to start Create System Users.
[FAILED] Failed to start Create Static Device Nodes in /dev.
[FAILED] Failed to start Journal Service.
[FAILED] Failed to start Journal Service.
[FAILED] Failed to start Journal Service.
[FAILED] Failed to start Journal Service.
[FAILED] Failed to start Journal Service.
[FAILED] Failed to listen on Journal Audit Socket.
[FAILED] Failed to start Journal Service.
[FAILED] Failed to start Create Volatile Files and Directories.
[FAILED] Failed to start Update UTMP about System Boot/Shutdown.
[FAILED] Failed to start Rebuild Journal Catalog.
[FAILED] Failed to start Update is Completed.
[FAILED] Failed to start Login Service.
[FAILED] Failed to start Login Service.
[FAILED] Failed to start Permit User Sessions.
[FAILED] Failed to start Login Service.
[FAILED] Failed to start Login Service.
[FAILED] Failed to start Login Service.
[FAILED] Failed to start Login Service.
[FAILED] Failed to start End the test.
[FAILED] Failed unmounting /run/systemd/nspawn/incoming.
[FAILED] Failed unmounting Temporary Directory (/tmp).
```

https://ci.centos.org/job/systemd-ci-build/533/artifact//index.html

It started the `testsuite.service`:

```
testsuite.service: Executing: /bin/sh -x -c 'systemctl --state=failed --no-legend --no-pager > /failed ; systemctl daemon-reload ; echo OK > /testok'
```

but I guess both systemctl commands failed. I'd say we should either add `-e` option to the `/bin/sh` or use `&&` instead of `;` as command separators to not mask such issues in the future.

**Comment by mrc0mmand** [comment]
Apparently, all subsequent errors come from failing generators:

```
[   32.789795] systemd[246]: Successfully forked off '(direxec)' as PID 258.
[   32.872868] systemd[246]: /usr/lib/systemd/system-generators/systemd-hibernate-resume-generator failed with exit status 1.
[   33.034210] systemd[246]: /usr/lib/systemd/system-generators/systemd-getty-generator failed with exit status 1.
[   33.077459] systemd[246]: /usr/lib/systemd/system-generators/systemd-rc-local-generator failed with exit status 1.
[   33.326420] systemd[246]: /usr/lib/systemd/system-generators/systemd-system-update-generator failed with exit status 1.
[   33.610276] systemd[246]: /usr/lib/systemd/system-generators/systemd-veritysetup-generator failed with exit status 1.
[   33.612144] systemd[246]: /usr/lib/systemd/system-generators/systemd-fstab-generator failed with exit status 1.
[   33.613444] systemd[246]: /usr/lib/systemd/system-generators/systemd-sysv-generator failed with exit status 1.
[   33.614693] systemd[246]: /usr/lib/systemd/system-generators/systemd-bless-boot-generator failed with exit status 1.
[   33.616437] systemd[246]: /usr/lib/systemd/system-generators/systemd-gpt-auto-generator failed with exit status 1.
[   33.617837] systemd[246]: /usr/lib/systemd/system-generators/systemd-run-generator failed with exit status 1.
[   33.619653] systemd[246]: /usr/lib/systemd/system-generators/systemd-debug-generator failed with exit status 1.
[   33.620957] systemd[246]: /usr/lib/systemd/system-generators/systemd-cryptsetup-generator failed with exit status 1.
[   33.642285] systemd[1]: (sd-executor) succeeded.
```

**Comment by mrc0mmand** [comment]
Well, the generators fail because of this:

```
$ export CC=clang
$ export CXX=clang++
$ meson build -Db_lundef=false -Db_sanitize=address
$ ninja -C build

$ rpm -q clang compiler-rt
clang-7.0.1-4.fc29.x86_64
compiler-rt-7.0.1-1.fc29.x86_64
$ rpm -ql compiler-rt | grep libclang_rt.asan-x86_64.so
/usr/lib64/clang/7.0.1/lib/libclang_rt.asan-x86_64.so
/usr/lib64/clang/7.0.1/lib/linux/libclang_rt.asan-x86_64.so
$ md5sum /usr/lib64/clang/7.0.1/lib/linux/libclang_rt.asan-x86_64.so /usr/lib64/clang/7.0.1/lib/libclang_rt.asan-x86_64.so
2c91eb1568e9e80c820b0ec69f162dd5  /usr/lib64/clang/7.0.1/lib/linux/libclang_rt.asan-x86_64.so
2c91eb1568e9e80c820b0ec69f162dd5  /usr/lib64/clang/7.0.1/lib/libclang_rt.asan-x86_64.so

$ LD_PRELOAD=/usr/lib64/clang/7.0.1/lib/libclang_rt.asan-x86_64.so SYSTEMD_LOG_LEVEL=debug build/systemd-fstab-generator t t t
==17674==Your application is linked against incompatible ASan runtimes.
```

**Comment by mrc0mmand** [comment]
Okay, apparently it's not *that* easy as I thought :-)

First of all, you need to compile systemd with `-shared-libasan` along with `-fsanitize=address` to make the shared DSO work as expected (as by default it's linked statically, apparently). After this, you can pre-load the ASan DSO using LD_PRELOAD, as with gcc. However, the `-shared-libasan` switch has an unfortunate side-effect, which results in an avalanche of errors regarding missing shared libraries and the need to explicitly set `LD_LIBRARY_PATH` everywhere, as the clang's ASan DSO is not in a standard library path.

After piling up kludge upon kludge, I'll rather pursue the second path and try to figure out why dbus doesn't work in the first place, when systemd is compiled with clang & ASan.

**Comment by mrc0mmand** [comment]
Looks like we're finally on the right track:

```
=================================================================
==273==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x7f28b72d0919  (/usr/lib/clang/8.0.0/lib/linux/libclang_rt.asan-x86_64.so+0x123919)
    #1 0x56481150c84f  (/usr/lib/systemd/systemd-journald+0x5784f)
    #2 0x7f28b5dd9ce2  (/usr/lib/libc.so.6+0x23ce2)

SUMMARY: AddressSanitizer: 1024 byte(s) leaked in 1 allocation(s).
-rw-r-----+ 1 root systemd-journal 8388608 May 26 06:44 /var/tmp/systemd-test.Iyiocw/journal/f78b19a916a84d6d919344686aff1b6a/system.journal
make: *** [Makefile:4: run] Error 1
```

I guess it needs the llvm-symbolizer to produce a useful output though.

**Comment by mrc0mmand** [comment]
So, after installing the `llvm-symbolizer` for the clang run, it finally gives us something useful:

```
=================================================================
==44==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x7f7ba7e03919 in malloc (/usr/lib/clang/8.0.0/lib/linux/libclang_rt.asan-x86_64.so+0x123919)
    #1 0x56424cbc184f in main /build/build/../src/journal/journald.c:30:16
    #2 0x7f7ba68fbce2 in __libc_start_main (/usr/lib/libc.so.6+0x23ce2)
```

I noticed, that even with my shenanigans with `LD_LIBRARY_PATH` in https://github.com/systemd/systemd/pull/12663, something still complains about ASan:

```
Installing /build/build/po/zh_CN.gmo to /var/tmp/systemd-test.Yx6tzD/root/usr/share/locale/zh_CN/LC_MESSAGES/systemd.mo
Installing /build/build/po/zh_TW.gmo to /var/tmp/systemd-test.Yx6tzD/root/usr/share/locale/zh_TW/LC_MESSAGES/systemd.mo
==12738==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
==12769==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
'/var/tmp/systemd-test.Yx6tzD/root/usr/bin/init' -> '../lib/systemd/systemd'
mkdir: created directory '/var/tmp/systemd-test.Yx6tzD/root/usr/lib/environment.d'
'/var/tmp/systemd-test.Yx6tzD/root/usr/lib/environment.d/99-environment.conf' -> '../../../etc/environment'
'/var/tmp/systemd-test.Yx6tzD/root/usr/bin/resolvconf' -> 'resolvectl'
'/var/tmp/systemd-test.Yx6tzD/root/usr/bin/systemd-resolve' -> 'resolvectl'
```

If I do `ldconfig <path-to-libclang_rt.asan>` instead of `LD_LIBRARY_PATH=<path-to-libclang_rt.asan` the issue seems to go away. Either way, it doesn't seem to have any visible impact on the results, and I'd like to avoid toying around with `ldconfig` on the host system, in case someone runs these tests locally :-)

**Comment by mrc0mmand** [comment]
UBsan seems to work as expected as well:

```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/journal/journald.c:30:26 in 
../src/journal/journald.c:30:26: runtime error: signed integer overflow: 2147483647 + 10 cannot be represented in type 'int'
    #0 0x5576701b2893 in main /build/build/../src/journal/journald.c:30:26
    #1 0x7f138ca63ce2 in __libc_start_main (/usr/lib/libc.so.6+0x23ce2)
    #2 0x5576701b23ed in _start (/usr/lib/systemd/systemd-journald+0x573ed)

```

**Comment by mrc0mmand** [comment]
@evverx I considered dropping man-page generation from sanitizer runs to speed things up. Is there any reason why it should stay as it is? After all, it's being tested by both standard runs and there's basically nothing which should be run under sanitizers.

**Comment by evverx** [comment]
@mrc0mmand my understanding was that the documentation is generated to make the scripts consistent with each other (I'm not exactly sure what that means though :-). If it's possible to turn it off when it's unnecessary, I think it should be turned off.

**Comment by evverx** [comment]
@mrc0mmand it's somewhat tangential to this PR but I'm wondering if you're planning to run systemd-networkd-test.py under ASan+UBSan now that it doesn't seem to be flaky on Arch any more?

**Comment by mrc0mmand** [comment]
> @mrc0mmand it's somewhat tangential to this PR but I'm wondering if you're planning to run systemd-networkd-test.py under ASan+UBSan now that it doesn't seem to be flaky on Arch any more?

After one of your comments showing partial results of a test run, it's definitely something I'd like to try out as soon as possible. Given we'd manage to make it work, it might substantially increase the runtime of the ASan+UBsan job, but I'd say it might be worth it :-)

**Comment by evverx** [comment]
I think it's worth it :-) especially when it comes to code written in C :-) With this PR merged it'll be safe to say that the basics are covered but `systemd-networkd`, `systemd-resolved`, `systemd-logind` and so on are still in a limbo so to speak leading to issues like https://github.com/systemd/systemd/issues/9511 every time anyone (somehow it's usually me :-) tries to run them under ASan+UBsan.

**Pull request merged**
