### PR TITLE
agent: use distro meson on CentOS 7

### PR DESCRIPTION
**Pull request by mrc0mmand**
to catch compatibility issues with older meson versions

### CODE REVIEW

**Comment by evverx** [comment]
It seems `meson ... --optimization=g` below should be replaced with `CFLAGS=-Og CXXFLAGS=-Og meson ...` or with `-Dc_args=... -Dcpp_args` if those are supported there.

**Comment by evverx** [comment]
Though I don't think whatever is passed via `c_args` is passed on to the fuzzers so it seems `CFLAGS` is the only option that works

**Comment by mrc0mmand** [comment]
> It seems `meson ... --optimization=g` below should be replaced with `CFLAGS=-Og CXXFLAGS=-Og meson ...` or with `-Dc_args=... -Dcpp_args` if those are supported there.

Ah, thanks, missed this one!



> Though I don't think whatever is passed via `c_args` is passed on to the fuzzers so it seems `CFLAGS` is the only option that works

I guess this doesn't matter here, since CentOS 7 has a pretty old gcc without UBSan, so fuzzers are skipped there anyway.

**Comment by mrc0mmand** [comment]
Also, as it failed (as expected) with ` ERROR: Tried to access unknown option "optimization".` I pointed it to https://github.com/systemd/systemd/pull/15937 to check if everything works as expected.

**Pull request merged**
