### PR TITLE
debug-only: test the btrfs-related changes

### PR DESCRIPTION
**Pull request by mrc0mmand**

### CODE REVIEW

**Comment by yuwata** [comment]
Hm?? I cannot catch why the CI failed now. A garbage image exists on the CI env? Or did I something wrong in the last push?

**Comment by mrc0mmand** [comment]
It failed the same way twice in a row.... I'll take a closer look.

**Comment by yuwata** [comment]
It seems my fault. I will fix the issue. Sorry for the noise.

**Comment by mrc0mmand** [comment]
> It seems my fault. I will fix the issue. Sorry for the noise.

Sweet, no problem!

**Comment by yuwata** [comment]
Should be fixed now. Please re-trigger again.

**Comment by yuwata** [comment]
Yay! It's green now!

**Comment by mrc0mmand** [comment]
rebuild this please

**Comment by mrc0mmand** [comment]
Looks like it passed the *stress test* as well, nice!

**Pull request closed without merging**
