### PR TITLE
vagrant: add Vagrantfiles to build test VM based on Fedora Rawhide

### PR DESCRIPTION
**Pull request by msekletar**

### CODE REVIEW

**Comment by msekletar** [comment]
Hi @mrc0mmand,

Here are super basic Vagrantfiles for Rawhide support. One is intended as a base for some sort of `make-cache` script. Second then uses output of box cache build process and compiles and installs latest systemd master and selinux-policy (from rawhide). The basic test scenario should be just rebooting the machine and checking list of AVCs,USER_AVCs and SELinux errors. I think that it should be sufficient to run this test just once per day.

**Comment by mrc0mmand** [comment]
retest this please

**Comment by mrc0mmand** [comment]
@msekletar Thanks for the scripts!

I made some prep commits on the side and then rebased them on top of this PR to make things easier & cleaner. Most of the stuff seems to be working, but I can't seem to build the latest selinux-policy RPM for some reason. I tried it locally in a rawhide container as well and got the same error:

```
[root@366a4706ada3 /]# fedpkg clone -a selinux-policy
Cloning into 'selinux-policy'...
remote: Enumerating objects: 109387, done.
remote: Counting objects: 100% (109387/109387), done.
remote: Compressing objects: 100% (22143/22143), done.
remote: Total 109387 (delta 86905), reused 109295 (delta 86820), pack-reused 0
Receiving objects: 100% (109387/109387), 54.93 MiB | 920.00 KiB/s, done.
Resolving deltas: 100% (86905/86905), done.
[root@366a4706ada3 /]# cd selinux-policy/
[root@366a4706ada3 selinux-policy]# fedpkg local
Downloading selinux-policy-f1505fc.tar.gz
######################################################################## 100.0%
Downloading selinux-policy-contrib-dad9c76.tar.gz
######################################################################## 100.0%
Downloading container-selinux.tgz
######################################################################## 100.0%
Downloading macro-expander
######################################################################## 100.0%
error: Bad source: /selinux-policy/selinux-policy-6c91ffd.tar.gz: No such file or directory

Could not execute local: rpmbuild --define '_sourcedir /selinux-policy' --define '_specdir /selinux-policy' --define '_builddir /selinux-policy' --define '_srcrpmdir /selinux-policy' --define '_rpmdir /selinux-policy' --define 'dist %{?distprefix}.fc34' --define 'fedora 34' --eval '%undefine rhel' --define 'fc34 1' -ba /selinux-policy/selinux-policy.spec 2>&1 | tee .build-3.14.7-9.fc34.log
```

Do you happen to know what's going on?

**Comment by mrc0mmand** [comment]
> @msekletar Thanks for the scripts!
> 
> I made some prep commits on the side and then rebased them on top of this PR to make things easier & cleaner. Most of the stuff seems to be working, but I can't seem to build the latest selinux-policy RPM for some reason. I tried it locally in a rawhide container as well and got the same error:
> 
> ```
> [root@366a4706ada3 /]# fedpkg clone -a selinux-policy
> Cloning into 'selinux-policy'...
> remote: Enumerating objects: 109387, done.
> remote: Counting objects: 100% (109387/109387), done.
> remote: Compressing objects: 100% (22143/22143), done.
> remote: Total 109387 (delta 86905), reused 109295 (delta 86820), pack-reused 0
> Receiving objects: 100% (109387/109387), 54.93 MiB | 920.00 KiB/s, done.
> Resolving deltas: 100% (86905/86905), done.
> [root@366a4706ada3 /]# cd selinux-policy/
> [root@366a4706ada3 selinux-policy]# fedpkg local
> Downloading selinux-policy-f1505fc.tar.gz
> ######################################################################## 100.0%
> Downloading selinux-policy-contrib-dad9c76.tar.gz
> ######################################################################## 100.0%
> Downloading container-selinux.tgz
> ######################################################################## 100.0%
> Downloading macro-expander
> ######################################################################## 100.0%
> error: Bad source: /selinux-policy/selinux-policy-6c91ffd.tar.gz: No such file or directory
> 
> Could not execute local: rpmbuild --define '_sourcedir /selinux-policy' --define '_specdir /selinux-policy' --define '_builddir /selinux-policy' --define '_srcrpmdir /selinux-policy' --define '_rpmdir /selinux-policy' --define 'dist %{?distprefix}.fc34' --define 'fedora 34' --eval '%undefine rhel' --define 'fc34 1' -ba /selinux-policy/selinux-policy.spec 2>&1 | tee .build-3.14.7-9.fc34.log
> ```
> 
> Do you happen to know what's going on?

Ah, nevermind, the original snippet is missing the `./make-rhat-patches.sh` step, which updates the SHA references.

**Comment by mrc0mmand** [comment]
@msekletar the pipeline seems to be working. I dropped the make-cache stuff for this specific box, as the rawhide box is rebuilt pretty frequently, so the update phase doesn't take much time (the longest part is now the selinux-policy compilation).

Also, I drafted up a simple test script, which runs after the machine is rebooted with the just compiled systemd & SELinux. So far it just saves the SELinux state and checks for AVCs since boot (and it has already found something, see the [respective log file](https://jenkins-systemd.apps.ocp.ci.centos.org/job/ci-build/161/artifact//artifacts_all/artifacts_mQCgLr/vagrant-logs.4KV/vagrant-rawhide-selinux-testsuite.8VC/avc-check_FAIL.log)). I'm not sure what is your idea of what should be tested, so please feel free to tweak that script to your liking.

**Comment by mrc0mmand** [comment]
Hmpf, it looks like the Vagrant images are not always built. At least they're missing from today's snapshot:

image

**Comment by msekletar** [comment]
We have discussed with @mrc0mmand offline that we need to cache the rawhide image locally. Hopefully that shouldn't be too much hassle.

Btw, @mrc0mmand, I think the script that you drafted is good enough for now. I'd like to have CI job running in this super basic form at least for couple of weeks before we try to extend it. 

Is there anything else that we need at this point to move this forward (except rawhide image caching of course)?

**Comment by mrc0mmand** [comment]
> 
> Is there anything else that we need at this point to move this forward (except rawhide image caching of course)?

Not really, right now I'm waiting for a Vagrant image to appear, since there hasn't been one for the past three days (https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Cloud/x86_64/images/).

**Comment by msekletar** [comment]
Hi @mrc0mmand, it seems that fresh batch of Rawhide Vagrant images just landed yesterday.

**Pull request merged**
