### PR TITLE
vagrant: reload dbus policies before running systemd-networkd-tests.py

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by yuwata** [comment]
```
Got message type=error sender=org.freedesktop.DBus destination=:1.728 path=n/a interface=n/a member=n/a cookie=3 reply_cookie=3 signature=s error-name=org.freedesktop.DBus.Error.AccessDenied error-message=Rejected send message, 2 matched rules; type="method_call", sender=":1.728" (uid=0 pid=6256 comm="/build/build/resolvectl dns dummy98 10.10.10.12 10") interface="org.freedesktop.network1.Manager" member="SetLinkDNS" error name="(unset)" requested_reply="0" destination="org.freedesktop.network1" (uid=981 pid=6233 comm="/build/build/systemd-networkd ")
```

**Comment by mrc0mmand** [comment]
@yuwata all Vagrant jobs should now use the latest gcc/kernel once again (since #146 was merged), so I dropped the workarounds for that from your PR.

**Comment by yuwata** [comment]
@mrc0mmand Thanks.

**Comment by yuwata** [comment]
@mrc0mmand I found the root of the issue. With sanitizers, the dbus config file is not the one provided by the current git master. So, systemd-networkd-tests.py cannot use new bus methods. Please make sure that the file `/usr/share/dbus-1/system.d/org.freedesktop.network1.conf` is provided by the build directory.

**Comment by mrc0mmand** [comment]
> @mrc0mmand I found the root of the issue. With sanitizers, the dbus config file is not the one provided by the current git master. So, systemd-networkd-tests.py cannot use new bus methods. Please make sure that the file `/usr/share/dbus-1/system.d/org.freedesktop.network1.conf` is provided by the build directory.

Thanks a lot for the investigation! That actually makes sense, as we intentionally skip the `ninja -C build install` step in sanitizer runs to improve stability of the SUT. Will definitely look into it to find a reasonable compromise.

**Comment by mrc0mmand** [comment]
@yuwata I pushed a potential fix. It's not particularly nice, but I'm not sure if there's a way to tell meson which files to install, instead of installing everything (at least I couldn't find any).

**Comment by yuwata** [comment]
> we intentionally skip the `ninja -C build install` step in sanitizer runs to improve stability of the SUT.

I see. Thats's why `test_udev_driver`, which was dropped by https://github.com/systemd/systemd/pull/12984, failed in the sanitizer CI. I will re-enable the test.

**Pull request merged**
