### PR TITLE
debug-only: run TEST-50-DISSECT in a loop

### PR DESCRIPTION
**Pull request by mrc0mmand**
to debug systemd/systemd#16859

### CODE REVIEW

**Comment by mrc0mmand** [comment]
retest this please

**Comment by mrc0mmand** [comment]
retest this please

**Comment by mrc0mmand** [comment]
retest this

**Comment by mrc0mmand** [comment]
retest this

**Comment by mrc0mmand** [comment]
retest this

**Comment by mrc0mmand** [comment]
retest this please

**Comment by poettering** [comment]
retest this please

**Comment by poettering** [comment]
retest this please

**Comment by poettering** [comment]
retest this please

**Pull request closed without merging**
